// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrRSagS7NwRZBQcUsl0X-JJBLXzYDqtBo',
    appId: '1:1007940080695:web:48112e99737c9b06ac5bb2',
    messagingSenderId: '1007940080695',
    projectId: 'mvvm-25c0e',
    authDomain: 'mvvm-25c0e.firebaseapp.com',
    storageBucket: 'mvvm-25c0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoVIKRWcahIROszvmndnZ7B31rPhCvAGQ',
    appId: '1:1007940080695:android:bae92474a6dd1977ac5bb2',
    messagingSenderId: '1007940080695',
    projectId: 'mvvm-25c0e',
    storageBucket: 'mvvm-25c0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxBeDSJSb0bFoGMdlCI5iPG9YnGJDu3f8',
    appId: '1:1007940080695:ios:806841028a8158e4ac5bb2',
    messagingSenderId: '1007940080695',
    projectId: 'mvvm-25c0e',
    storageBucket: 'mvvm-25c0e.appspot.com',
    iosClientId: '1007940080695-5cnrm9m61bln51929c1n47nlju25fp4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvvmDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxBeDSJSb0bFoGMdlCI5iPG9YnGJDu3f8',
    appId: '1:1007940080695:ios:806841028a8158e4ac5bb2',
    messagingSenderId: '1007940080695',
    projectId: 'mvvm-25c0e',
    storageBucket: 'mvvm-25c0e.appspot.com',
    iosClientId: '1007940080695-5cnrm9m61bln51929c1n47nlju25fp4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvvmDesign',
  );
}
